[package]
name = "technomancy_core"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-only"
description = "The technomancy core data types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
