[package]
name = "card_rule_engine"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
nom-supreme = "0.8.0"
uuid = { version = "1.2.1", features = ["v4"] }
